[2013-07-12 00:01:01] log.ERROR: exception 'InvalidArgumentException' with message 'View [user.connexion] not found.' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:123
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(64): Illuminate\View\FileViewFinder->findInPaths('user.connexion', Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\View\Environment.php(115): Illuminate\View\FileViewFinder->find('user.connexion')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\View\Environment->make('user.connexion')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\controllers\UserController.php(7): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\controllers\UserController.php(7): Illuminate\Support\Facades\View::make('user.connexion')
#5 [internal function]: UserController->getEdit('1')
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getEdit', Array)
#8 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getEdit', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1')
#10 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#11 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#12 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-07-12 00:22:51] log.ERROR: exception 'ErrorException' with message 'Undefined variable: account' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:59
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(59): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 59, Array)
#1 [internal function]: {closure}()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(180): Illuminate\Routing\Router->group(Array, Object(Closure))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(77): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(77): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#8 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#9 {main} [] []
[2013-07-12 00:23:10] log.ERROR: exception 'ErrorException' with message 'Missing argument 1 for {closure}()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:56
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(56): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'J:\xampp2\htdoc...', 56, Array)
#1 [internal function]: {closure}()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(180): Illuminate\Routing\Router->group(Array, Object(Closure))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(77): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(77): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#8 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#9 {main} [] []
[2013-07-12 00:24:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:78
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 00:24:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:78
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 00:24:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:78
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 00:29:55] log.ERROR: exception 'ErrorException' with message 'Undefined variable: account' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:60
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(60): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 60, Array)
#1 [internal function]: {closure}()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(180): Illuminate\Routing\Router->group(Array, Object(Closure))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(82): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(82): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#8 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#9 {main} [] []
[2013-07-12 00:30:45] log.ERROR: exception 'ErrorException' with message 'Undefined variable: server' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:60
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(60): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 60, Array)
#1 [internal function]: {closure}()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(180): Illuminate\Routing\Router->group(Array, Object(Closure))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(82): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(82): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#8 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#9 {main} [] []
[2013-07-12 00:36:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'user' (T_STRING), expecting '{'' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:67
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 10:51:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:47
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 10:52:02] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:47
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 10:52:14] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'UrlSubdomain' not found' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:29
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 10:53:34] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RouteCollection, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 19 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(19): Symfony\Component\Routing\Generator\UrlGenerator->__construct()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 10:57:25] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Monolog\Formatter\LineFormatter' not found' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:3
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 10:57:42] log.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Routing\RouteCollection::add() must be an instance of Symfony\Component\Routing\Route, instance of Illuminate\Support\Facades\Route given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 19 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\RouteCollection.php:79
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\RouteCollection.php(79): Illuminate\Exception\Handler->handleError(4096, 'Argument 2 pass...', 'J:\xampp2\htdoc...', 79, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(19): Symfony\Component\Routing\RouteCollection->add('show_post', Object(Illuminate\Support\Facades\Route))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 10:58:20] log.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Routing\RouteCollection::add() must be an instance of Symfony\Component\Routing\Route, instance of Illuminate\Support\Facades\Route given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 18 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\RouteCollection.php:79
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\RouteCollection.php(79): Illuminate\Exception\Handler->handleError(4096, 'Argument 2 pass...', 'J:\xampp2\htdoc...', 79, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(18): Symfony\Component\Routing\RouteCollection->add('show_post', Object(Illuminate\Support\Facades\Route))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 10:59:05] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'UrlGenerator' not found' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:22
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 10:59:15] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'SymfonyGenerator' not found' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:28
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:00:19] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RouteCollection, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 27 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(27): Symfony\Component\Routing\Generator\UrlGenerator->__construct()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:00:34] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RouteCollection, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 27 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(27): Symfony\Component\Routing\Generator\UrlGenerator->__construct()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:00:35] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RouteCollection, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 27 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(27): Symfony\Component\Routing\Generator\UrlGenerator->__construct()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:00:35] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RouteCollection, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 27 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(27): Symfony\Component\Routing\Generator\UrlGenerator->__construct()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:00:37] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\Routing\Generator\UrlGenerator::isValidUrl()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:00:58] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:00:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:00:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:00:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:00:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:01:00] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:01:06] log.ERROR: exception 'ErrorException' with message 'Undefined variable: symfonyGenerator' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:33
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(33): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 33, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:01:07] log.ERROR: exception 'ErrorException' with message 'Undefined variable: symfonyGenerator' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:33
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(33): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 33, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:03:40] log.ERROR: exception 'Symfony\Component\Routing\Exception\RouteNotFoundException' with message 'Unable to generate a URL for the named route "show_post" as such route does not exist.' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:134
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(22): Symfony\Component\Routing\Generator\UrlGenerator->generate('show_post', Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:03:54] log.ERROR: exception 'ErrorException' with message 'Undefined variable: tail' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:18
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(18): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 18, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/maintenance', 'test')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:05:15] log.ERROR: exception 'ErrorException' with message 'array_replace(): Argument #3 is not an array' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:151
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_replace()...', 'J:\xampp2\htdoc...', 151, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(151): array_replace(Array, Array, '4')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(140): Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(Array, Array, Array, Array, '4', 'show_post', false, Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(29): Symfony\Component\Routing\Generator\UrlGenerator->generate('show_post', '4')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#8 {main} [] []
[2013-07-12 11:05:15] log.ERROR: exception 'ErrorException' with message 'array_replace(): Argument #3 is not an array' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:151
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'array_replace()...', 'J:\xampp2\htdoc...', 151, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(151): array_replace(Array, Array, '4')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(140): Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(Array, Array, Array, Array, '4', 'show_post', false, Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(29): Symfony\Component\Routing\Generator\UrlGenerator->generate('show_post', '4')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#8 {main} [] []
[2013-07-12 11:07:42] log.ERROR: exception 'ErrorException' with message 'Undefined variable: parameters' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:18
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(18): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 18, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(30): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:07:52] log.ERROR: exception 'ErrorException' with message 'Object of class Symfony\Component\Routing\RequestContext could not be converted to string' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:26
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(26): Illuminate\Exception\Handler->handleError(4096, 'Object of class...', 'J:\xampp2\htdoc...', 26, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(30): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:08:14] log.ERROR: exception 'ErrorException' with message 'Object of class Symfony\Component\Routing\RequestContext could not be converted to string' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:26
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(26): Illuminate\Exception\Handler->handleError(4096, 'Object of class...', 'J:\xampp2\htdoc...', 26, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(30): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:13:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'break' (T_BREAK)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:41
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:14:49] log.ERROR: exception 'ErrorException' with message 'Non-static method Symfony\Component\HttpFoundation\Request::getBaseUrl() should not be called statically' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(19): Illuminate\Exception\Handler->handleError(2048, 'Non-static meth...', 'J:\xampp2\htdoc...', 19, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(19): Symfony\Component\HttpFoundation\Request::getBaseUrl()
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:16:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\Request::url()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:16:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\Request::url()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:17:06] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\Request::path()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:17:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\Request::path()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:17:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\Request::path()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:17:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\Request::path()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:17:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Symfony\Component\HttpFoundation\Request::path()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:18:10] log.ERROR: exception 'ErrorException' with message 'Use of undefined constant Request - assumed 'Request'' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:19
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(19): Illuminate\Exception\Handler->handleError(8, 'Use of undefine...', 'J:\xampp2\htdoc...', 19, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:20:43] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$pattern' (T_VARIABLE)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:42
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:27:07] log.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RequestContext, string given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 33 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 2 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(33): Symfony\Component\Routing\Generator\UrlGenerator->__construct(Object(Symfony\Component\Routing\RouteCollection), '/')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:27:17] log.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RequestContext, string given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 33 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 2 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(33): Symfony\Component\Routing\Generator\UrlGenerator->__construct(Object(Symfony\Component\Routing\RouteCollection), '$context')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:27:43] log.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RequestContext, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 32 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 2 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(32): Symfony\Component\Routing\Generator\UrlGenerator->__construct(Object(Symfony\Component\Routing\RouteCollection))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:28:13] log.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RequestContext, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 30 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 2 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(30): Symfony\Component\Routing\Generator\UrlGenerator->__construct(Object(Symfony\Component\Routing\RouteCollection))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:28:13] log.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Symfony\Component\Routing\Generator\UrlGenerator::__construct() must be an instance of Symfony\Component\Routing\RequestContext, none given, called in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php on line 30 and defined' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:89
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php(89): Illuminate\Exception\Handler->handleError(4096, 'Argument 2 pass...', 'J:\xampp2\htdoc...', 89, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(30): Symfony\Component\Routing\Generator\UrlGenerator->__construct(Object(Symfony\Component\Routing\RouteCollection))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#6 {main} [] []
[2013-07-12 11:32:58] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method UrlSubdomain::valid()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:22
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:33:22] log.ERROR: exception 'ErrorException' with message 'Undefined variable: https' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:21
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(21): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 21, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:33:31] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method UrlSubdomain::base()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:23
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:34:06] log.ERROR: exception 'ErrorException' with message 'Undefined variable: asset' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:27
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(27): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 27, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:34:17] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method UrlSubdomain::result()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:38
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:35:42] log.ERROR: exception 'ErrorException' with message 'Undefined variable: https' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:31
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(31): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 31, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:36:49] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method UrlSubdomain::result()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:34
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:38:00] log.ERROR: exception 'ErrorException' with message 'Undefined variable: url' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:34
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(34): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 34, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:39:13] log.ERROR: exception 'ErrorException' with message 'Undefined variable: url' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:36
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php(36): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 36, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(29): UrlSubdomain::to('/ROUTE', 'SUBDOMAIn', Array)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#5 {main} [] []
[2013-07-12 11:40:41] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'implode' (T_STRING)' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\libraries\UrlSubdomain.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:41:31] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'UrlSubdomain' (T_STRING), expecting ',' or ';'' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:30
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:47:48] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function URLSubdomain()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\storage\views\2250f3a05d6ce8976e395bc3be589787:7
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:47:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function URLSubdomain()' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\storage\views\2250f3a05d6ce8976e395bc3be589787:7
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 11:56:35] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:56:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:57:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:57:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:57:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:57:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:57:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:57:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:58:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:59:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:59:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 11:59:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1438
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-12 12:05:37] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Using $this when not in object context' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:58
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-12 12:06:39] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:58
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(58): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'J:\xampp2\htdoc...', 58, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#4 {main} [] []
[2013-07-12 12:11:43] log.ERROR: exception 'ErrorException' with message 'Undefined variable: username' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\models\validators\connexion.php:24
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\models\validators\connexion.php(24): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 24, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\controllers\LoginController.php(15): validators_connexion->login(0)
#2 [internal function]: LoginController->postLogin()
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-07-12 12:12:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: username' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\models\validators\connexion.php:25
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\models\validators\connexion.php(25): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'J:\xampp2\htdoc...', 25, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\controllers\LoginController.php(15): validators_connexion->login(0)
#2 [internal function]: LoginController->postLogin()
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-07-12 12:13:50] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Auth\Guard::login() must implement interface Illuminate\Auth\UserInterface, integer given' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Auth\Guard.php:332
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(332): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'J:\xampp2\htdoc...', 332, Array)
#1 [internal function]: Illuminate\Auth\Guard->login(1)
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Manager.php(127): call_user_func_array(Array, Array)
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Support\Manager->__call('login', Array)
#4 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Auth\AuthManager->login(1)
#5 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\models\User.php(42): Illuminate\Support\Facades\Facade::__callStatic('login', Array)
#6 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\models\User.php(42): Illuminate\Support\Facades\Auth::login(1)
#7 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\controllers\LoginController.php(17): User::connexion(1)
#8 [internal function]: LoginController->postLogin()
#9 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#10 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#11 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#13 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#14 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#15 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(522): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(497): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(50): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2013-07-12 12:15:34] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php:58
Stack trace:
#0 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\app\routes.php(58): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'J:\xampp2\htdoc...', 58, Array)
#1 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\vendor\laravel\framework\src\Illuminate\Foundation\start.php(251): require('J:\xampp2\htdoc...')
#2 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\bootstrap\start.php(66): require('J:\xampp2\htdoc...')
#3 J:\xampp2\htdocs\lara_vieassoc\Dropbox\Dev\www-vieassoc\public\index.php(36): require_once('J:\xampp2\htdoc...')
#4 {main} [] []
